### ISSUE TITLE
unable to modify the baseurl

### ISSUE THREAD

**Issue by malkova** [cangencer/salesforce-oauth2#3]
It would be nice to have a setter methods to change the hardcoded baseUrl, authorizeUrl, tokenUrl.
This would help during the development process to point to dev instance of  the platform.

**Comment by cangencer** [comment]
It's already possible to pass in another baseUrl by specifying "base_url" in the options.

The authorizeUrl and tokenUrl are relative so they should not need to be changed.

**Comment by malkova** [comment]
got it, that works.
